### ISSUE TITLE
Training log

### ISSUE THREAD

**Issue by shawrby** [aharley/bev_baseline#12]
For test, I'm trying to train a Cam+Rad BEV model with a NuScenes mini dataset.
But, iou_v is nan as shown below.
![image](https://user-images.githubusercontent.com/54407464/199632010-48bc2661-6f3a-4469-8b25-569b0c0bb59f.png)

Could you please share your training log for debugging?

**Comment by aharley** [comment]
This nan is nothing to worry about. At the beginning of a training run, there is no `iou_v` to report. Just wait until a val step!

**Comment by shawrby** [comment]
> This nan is nothing to worry about. At the beginning of a training run, there is no `iou_v` to report. Just wait until a val step! 

Oh. Thank you!

Could you share the your log for comparison with my train/val log?
