### ISSUE TITLE
Negative loss

### ISSUE THREAD

**Issue by shawrby** [aharley/bev_baseline#13]
I am currently training the bev model with my dataset.
However, after enough steps, the total loss becomes negative as shown below.
![image](https://user-images.githubusercontent.com/54407464/199863243-cf2873f8-ce9d-46b2-be26-7350b8dffbc1.png)

After debugging, when calculating **uncertainty_loss**(ce_uncertainty_loss, center_uncertainty_loss, offset_uncertainty_loss),
**weight**(model.module.ce_weight, model.module.center_weight, model.module.offset_weight) is negative.
![image](https://user-images.githubusercontent.com/54407464/199863326-ac67d75f-5033-4a79-a8b6-53d68f8351ef.png)

Are there any possible causes?

**Comment by aharley** [comment]
Negative loss is OK here. For context you can check these:
https://github.com/yaringal/multi-task-learning-example
https://arxiv.org/abs/1705.07115

**Comment by shawrby** [comment]
> Negative loss is OK here. For context you can check these:
> https://github.com/yaringal/multi-task-learning-example
> https://arxiv.org/abs/1705.07115

@aharley 

Thank you so much!
