### ISSUE TITLE
Can you explain the motivation and usage of "randomize reference cam augmentation"?

### ISSUE THREAD

**Issue by mingyangShang** [aharley/bev_baseline#18]
Firstly i think the motivation of this paper is very insightful and the conclusion is  solid enough, thanks the authors for your effort. 
I'm curious about the "**randomize reference cam augmentation**" mentioned in this paper. I found the first camera and the randomized camera are swapped in [code](https://github.com/aharley/simple_bev/blob/main/nuscenesdataset.py#L1026-L1052) to make sure the 0th cam is randomized referenced camera, but i don't understand what the motivation of this augmentation is and how it's done in detail. Can you explain it or provide the reference paper (if exists). Besides, the paper mentioned "We  have  observed  qualitatively  that  without this augmentation, the segmented cars have a slight bias forcertain orientations in certain positions; with the augmentation  added,  this  bias  disappears.",  can you show us the badcase with image to make it more intutive?

**Comment by aharley** [comment]
I don't have a reference and I don't have a qualitative image for this right now, but I think if you train it without this option, you'll produce the effect mentioned in the paper. It becomes especially clear if you create a video visualization: as a parked car shifts in position relative to the ego-car, its shape will morph in a way that looks similar to orientation change.

**Comment by mingyangShang** [comment]
Then what the motivation of this augmentation is and how it's done in detail?
