### ISSUE TITLE
"Lift" operation in code

### ISSUE THREAD

**Issue by Like2021** [aharley/bev_baseline#20]
Hi,

Thank you for your research.

Could you give me some tips about "Lift" operation in Code,

may be here:

https://github.com/aharley/simple_bev/blob/be46f0ef71960c233341852f3d9bc3677558ab6d/utils/vox.py#L291-L341

**Comment by aharley** [comment]
The idea here is: for each 3D coordinate in the `mem` grid (aka the BEV meshgrid but with a vertical axis), take a bilinear sample at the pixel location where this coordinate projects.

**Comment by erivera1802** [comment]
@aharley that means, several 3d cells which are projected to the same pixel will be assigned the same 2D feature?

**Comment by aharley** [comment]
Yes. But I think it's rare for the features to be exactly the same, because really the 3D coordinates land in floating point (subpixel) locations, and we take bilinear samples.
