### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by ygjwd12345** [aharley/bev_baseline#21]
Thanks for your wonderful work.
I am trying to reproduce it, and the result looks great.
So I want to further analyze the result.
Could you share your visualization command?

**Comment by aharley** [comment]
It's here: https://github.com/aharley/simple_bev/blob/main/vis_nuscenes.py

**Comment by ygjwd12345** [comment]
would you mind giving me a demo command?

**Comment by aharley** [comment]
what about `python vis_nuscenes.py`

**Comment by ygjwd12345** [comment]
something like
`
python eval_nuscenes.py \
       --batch_size=16 \
       --data_dir='../nuscenes' \
       --log_dir='logs_eval_nuscenes_bevseg' \
       --init_dir='checkpoints/8x5_5e-4_rgb12_22:43:46' \
       --res_scale=2 \
       --device_ids=[0,1,2,3]
`

**Comment by aharley** [comment]
I think if you adapt this slightly to the vis script, it will work... Can you try it and let me know a specific issue you can't fix?

**Comment by ygjwd12345** [comment]
my problem. I will test first.

**Comment by ygjwd12345** [comment]
Thank you so much.
I have successfully visualized the model.
the command like
`python vis_nuscenes.py  --data_dir='/home/xx/data/datatset/nuscenes/trainval' --init_dir='checkpoints/16x5_3e-4s_rgb_mine_09:22:16'`
