### ISSUE TITLE
pre-trained models seemed to be unavailable

### ISSUE THREAD

**Issue by dadadadaguai** [aharley/bev_baseline#27]
Thanks for your great work！
A small problem，when I run the command to download the pre-trained models，the error shows that https://www.dropbox.com/s/n93ryvrqyiram56 could not to be connected，is there any netdisk to download the models？

**Comment by aharley** [comment]
That link currently works for me. Can you try pasting the link into a browser?

**Comment by dadadadaguai** [comment]
Oh，it's my fault
I use the VPPNNN and successfully download the models，maybe I made some mistake on typping the link
