### ISSUE TITLE
seg_bev label

### ISSUE THREAD

**Issue by shawrby** [aharley/bev_baseline#30]
Hi!

I have a question.

Checking seg_bev_g for analysis shows the following.

![image](https://user-images.githubusercontent.com/54407464/230264210-74899c49-cff6-4bec-bcd2-ee049a67b29a.png)

Why are the value(=color) different for each object?

**Comment by aharley** [comment]
That's just to prove that they are instance labels. You can convert them to semantic labels by thresholding (`seg>0`).

**Comment by shawrby** [comment]
Thank you for fast reply!

Then, is it correct to express the color value differently for each object?

Doesn't that have a impact on training?

**Comment by shawrby** [comment]
Oh, I just got it all figured out.

Thank you very much!!
