### ISSUE TITLE
No performance improvement after using radar data

### ISSUE THREAD

**Issue by cyn-liu** [aharley/bev_baseline#34]
Hi @aharley :

Thanks for your job, which give me some ideas.
In my BEV detection model, I Rasterisation the RADAR data and concatenated with the BEV feature output from LSS according to dimensions, but the result was 2-3 points lower.

Do you know why? Or tell me some potential problem.

**Comment by aharley** [comment]
Did you try rasterizing and concatenating the same way as in this repo? In this repo, it gives a very reliable boost.

**Comment by cyn-liu** [comment]
> Did you try rasterizing and concatenating the same way as in this repo? In this repo, it gives a very reliable boost.

@aharley 
I referred to the idea of `simple_bev` and did same radar preprocessing and concatenation method, but my BEV detection model adopts different projection method of  image features into BEV features,  I don't think this will affect the performance improvement brought by Radar.

I found the `simple_bev` uses the `InstanceNorm2d` normalization method, but my model uses `BN`, Is this the key reason why the model performance cannot be improved?

Best regards
Cynthia

**Comment by aharley** [comment]
I like to avoid BN in general, as it seems tricky to tune. If you are using a small/medium batch size, IN may indeed help stabilize things.
