### ISSUE TITLE
how to make figures of polar BEV figures

### ISSUE THREAD

**Issue by Deephome** [aharley/bev_baseline#42]
Your work is great! I want to know what software you use to make  figures like this, especially the polar BEV features with irregular shape.
![bev](https://simple-bev.github.io/images/2dtobev_orig.004_cropped.png)

Thank you!

**Comment by aharley** [comment]
Hi, thanks for the question. I drew this one line at a time in Keynote. Just rectangles and lines. I found a paper with a similar-looking polar thing and traced it to help get started.

**Comment by Deephome** [comment]
> 

thank you for your kind reply!
