### ISSUE TITLE
C+R pretrained model & Vis.

### ISSUE THREAD

**Issue by shawrby** [aharley/bev_baseline#5]
Thanks for the great research!

I have a few questions.

1. Is there cam + radar pretrained model? It seems that only camera models are available for download.
2. For continuous visualization (=video), what should I do?

**Comment by aharley** [comment]
1. Have you tried `get_rad_model.sh`?
2. Step1 is to run `vis_nuscenes.py` to export a lot of pngs to disk, and then step2 is to arrange the visualizations into a bigger per-frame collage (e.g., see `vis_collage.py`), and finally step3 is to convert the set of images into an mp4, using ffmpeg.

**Comment by RenSmith** [comment]
> 1. Have you tried `get_rad_model.sh`?
> 2. Step1 is to run `vis_nuscenes.py` to export a lot of pngs to disk, and then step2 is to arrange the visualizations into a bigger per-frame collage (e.g., see `vis_collage.py`), and finally step3 is to convert the set of images into an mp4, using ffmpeg.

Thanks for your great works.
I also met this problem. It seems the links in  `get_rad_model.sh` will jump to the same place the `get_rgb_model.sh` points to.
Also, following the command in `Training` can train a model with IOU 42 instead of 47.6. Is there any suggestion ?

**Comment by aharley** [comment]
Thanks. 

I pushed a fix for `get_rad_model.sh`. Can you try it again?

@RenSmith, are you reading this IOU from the on-the-fly evaluation, or did you do a full eval run?

**Comment by shawrby** [comment]
@aharley 

Both get_rad_model.sh and get_rgb_model.sh have the same problem as below.
![image](https://user-images.githubusercontent.com/54407464/187583928-886027fd-60d4-4573-abac-259766ba9f2d.png)

**Comment by aharley** [comment]
Hm interesting. For me it works. Can you try pasting the dropbox url into your browser, to see if that works at least?

**Comment by shawrby** [comment]
@aharley 
Oh good! Thanks again for your excellent research.
