### ISSUE TITLE
Dataset path error

### ISSUE THREAD

**Issue by sanjaychowdhry** [aharley/bev_baseline#54]
I am trying to run simpleBEV code on NuScenes full dataset, it is giving me path error.

  File "/home/sanjay.kumar/simple_bev/nuscenesdataset.py", line 1253, in compile_data
    nusc = NuScenes(version='v1.0-trainval'.format(version),
  File "/home/sanjay.kumar/anaconda3/envs/bev/lib/python3.10/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: ../../../data/datasets/public_datasets/nuScenes/nuScenes/trainval/v1.0-trainval

**Comment by sanjaychowdhry** [comment]
resolved

**Comment by sai-prakhya-ai** [comment]
@sanjaychowdhry - can you please tell how did you resolve this ?
