### ISSUE TITLE
 FAIL : Load model from simple_bev.onnx failed:Fatal error: org.pytorch.aten:instance_norm(-1) is not a registered function/op

### ISSUE THREAD

**Issue by zmtttt** [aharley/bev_baseline#58]
I have generated onnx.model ，I want to verify that how it works；
code：
model_path = 'simple_bev.onnx'
print("--begin inferenceSession--")
session = ort.InferenceSession(model_path)
print("--finish inferenceSessio--")

error：
 File "/root/miniconda3/envs/bev/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from simple_bev.onnx failed:Fatal error: org.pytorch.aten:instance_norm(-1) is not a registered function/op

**Comment by LiaoChengkk** [comment]
hello， can u show how to generate onnx model？
